[[redirects]]
  from = "/store/*"
  to = "/"
  force = true

[[redirects]]
  from = "/contact/"
  to = "/locations/greeley/"
  force = true

[[redirects]]
  from = "/services/detailing/"
  to = "/"
  force = true
